[build]
  # 发布目录
  publish = "."
  
  # 构建命令（静态站点不需要构建）
  command = "echo 'No build required for static site'"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"

# SPA重定向规则 - 这是关键！
[[redirects]]
  from = "/*"
  to = "/templates/login.html"
  status = 200

# 头部设置
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 