[build]
  # 发布目录（当前目录）
  publish = "."
  
  # 构建命令（对于静态站点，通常不需要）
  command = "echo 'Static site - no build required'"

[build.environment]
  # Python版本（如果需要）
  PYTHON_VERSION = "3.9"

# 重定向规则
[[redirects]]
  from = "/templates/*"
  to = "/templates/:splat"
  status = 200

# 防止直接访问数据文件
[[headers]]
  for = "/static/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

# 文件类型处理
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# SPA重定向规则 - 这是关键！
[[redirects]]
  from = "/*"
  to = "/templates/login.html"
  status = 200

# 头部设置
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff" 