[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install flask flask-cors']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python simple_railway_app.py' 