[phases.setup]
nixPkgs = ['python311', 'pip']

[phases.install]
cmds = ['pip install -r requirements_production.txt']

[phases.build]
cmds = ['echo "Build completed"']

[start]
cmd = 'python app.py'

[variables]
PYTHON_VERSION = '3.11'
FLASK_ENV = 'production' 