services:
  - type: web
    name: cyberwise-ai-backend
    env: python
    buildCommand: pip install -r requirements_production.txt
    startCommand: python app.py
    plan: free
    autoDeploy: false
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
