services:
  - type: web
    name: cyberwise-ai-backend-simple
    env: python
    buildCommand: "pip install -r requirements_simple.txt"
    startCommand: "python simple_app.py"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: PORT
        value: "10000"
