services:
  - type: web
    name: cyberwise-ai-backend
    env: python
    buildCommand: "pip install -r requirements_production.txt"
    startCommand: "python app.py"
    plan: starter # $7/月，2GB内存
    envVars:
      - key: PYTHON_VERSION
        value: "3.11"
      - key: FLASK_ENV
        value: "production"
      - key: PORT
        value: "10000"
