services:
  - type: web
    name: cyberwise-ai-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run_ai_server.py
    plan: free
    autoDeploy: false
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 5001
      - key: FLASK_ENV
        value: production
